"""SearXNG installer recipe.

Sets up a local SearXNG instance via Docker, with JSON output enabled so
the web_search tool can call it. The instance binds on host port 8888 by
default (8080 is too commonly used).

Constants are exposed at module level so the web_search backend can
import them — keeps the "what URL is SearXNG on?" answer single-sourced.
"""

from __future__ import annotations

import hashlib
import logging
from pathlib import Path

from openjarvis.installers.base import (
    Installer,
    VolumeMount,
    Wipeability,
)
from openjarvis.installers.primitives import (
    ConfigFile,
    DockerEnvCheck,
    DockerImage,
    DockerRun,
    WaitForHTTP,
)
from openjarvis.installers.registry import register_installer

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants — kept module-level so web_search/searxng_backend can import them
# ---------------------------------------------------------------------------

INSTALLER_ID = "web_search.searxng"
CONTAINER_NAME = "openjarvis-searxng"
IMAGE_REF = "searxng/searxng:latest"
HOST_PORT = 8888
CONTAINER_PORT = 8080
BASE_URL = f"http://localhost:{HOST_PORT}"
HEALTH_URL = f"{BASE_URL}/search?q=ping&format=json"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _settings_path() -> Path:
    """Return the host path for the SearXNG settings file.

    Resolves lazily against ``DEFAULT_CONFIG_DIR`` (falling back to
    ``~/.openjarvis``) so test fixtures can monkey-patch the config dir.
    """
    try:
        from openjarvis.core.config import DEFAULT_CONFIG_DIR

        base = Path(DEFAULT_CONFIG_DIR)
    except Exception:
        base = Path.home() / ".openjarvis"
    return base / "installers" / "searxng" / "settings.yml"


def _derive_secret_key() -> str:
    """Generate a stable, per-user secret key for SearXNG cookie signing.

    Derived from the user's home directory so it's deterministic across
    runs on the same machine but differs between users. This matters
    only if the SearXNG instance is exposed publicly — for a local-only
    instance it's effectively a no-op, but providing a unique value
    avoids SearXNG's "default secret_key" startup warning.
    """
    seed = f"openjarvis-searxng::{Path.home()}"
    return hashlib.sha256(seed.encode("utf-8")).hexdigest()


def _settings_yml() -> str:
    """Return the SearXNG settings.yml content.

    Crucially enables JSON output (off by default in SearXNG) so the
    web_search tool can parse machine-readable responses. Disables the
    rate limiter for local-only use.
    """
    secret = _derive_secret_key()
    return f"""# Generated by OpenJarvis — edit cautiously.
# To restore this file to defaults, use Settings → Storage → Restore defaults
# in the SearXNG connector card.

use_default_settings: true

server:
  # Cookie signing key. Derived from your home directory so it's stable
  # per-user. If you expose this SearXNG publicly, replace with a fresh
  # random value (`openssl rand -hex 32`).
  secret_key: "{secret}"
  # The rate limiter blocks repeated queries from the same client. Fine
  # for public instances; counter-productive when a single local agent
  # is hammering the API. Disable for local use.
  limiter: false
  image_proxy: true
  bind_address: "0.0.0.0"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  # Enable the JSON output format — REQUIRED for programmatic use.
  formats:
    - html
    - json

ui:
  static_use_hash: true
"""


# ---------------------------------------------------------------------------
# Installer recipe
# ---------------------------------------------------------------------------


SEARXNG_INSTALLER = Installer(
    installer_id=INSTALLER_ID,
    display_name="Local SearXNG",
    description=(
        "Self-hosted metasearch engine running in Docker. Aggregates "
        "results from Google, Bing, DuckDuckGo, Brave, and ~10 other "
        "engines with JSON output enabled for programmatic access."
    ),
    estimated_total_seconds=180,
    estimated_download_mb=350,
    steps=[
        DockerEnvCheck(),
        DockerImage(IMAGE_REF),
        ConfigFile(
            path=_settings_path(),
            content=_settings_yml(),
            item_id="searxng.config",
            description="SearXNG configuration (engines, JSON output, theme)",
        ),
        DockerRun(
            container_name=CONTAINER_NAME,
            image_ref=IMAGE_REF,
            ports={HOST_PORT: CONTAINER_PORT},
            volumes=[
                VolumeMount(
                    host_path=_settings_path(),
                    container_path="/etc/searxng/settings.yml",
                    item_id="searxng.config",
                    description="SearXNG configuration",
                    wipeability=Wipeability.REPLACEABLE,
                    # ConfigFile (declared above) owns this storage —
                    # DockerRun still stops itself for wipes but doesn't
                    # double-count the file in the Storage panel.
                    report_storage=False,
                ),
            ],
            restart="unless-stopped",
        ),
        WaitForHTTP(
            HEALTH_URL,
            expected_status=200,
            timeout=90,
            interval=2.0,
            what="SearXNG",
        ),
    ],
)


register_installer(SEARXNG_INSTALLER)


__all__ = [
    "BASE_URL",
    "CONTAINER_NAME",
    "HEALTH_URL",
    "HOST_PORT",
    "IMAGE_REF",
    "INSTALLER_ID",
    "SEARXNG_INSTALLER",
]
